

functions:
  general_params:
    root_dir: "C:\\Maor Nanikashvili\\thesis_pipeline\\Pipeline\\input\\data\\sentilet\\R20m"

  move_candidates_to_dataset:
    full_path_to_dataset: "C:\\Maor Nanikashvili\\thesis_pipeline\\Pipeline\\results\\sentilet_data\\full_dataset"
    full_path_general_input_dir: "C:\\Maor Nanikashvili\\thesis_pipeline\\Pipeline\\results\\sentilet_data\\patches_after_anno"

  check_for_seg_classes:
    folder_path: "C:\\Maor Nanikashvili\\thesis_pipeline\\Pipeline\\results\\sentilet_data\\patches_after_anno\\masks"

  create_masks_from_json_files:
    input_json_folder: "C:\\Maor Nanikashvili\\thesis_pipeline\\Pipeline\\results\\sentilet_data\\patches_anno\\images"
    output_mask_folder: "C:\\Maor Nanikashvili\\thesis_pipeline\\Pipeline\\results\\sentilet_data\\patches_anno\\anno_masks"
    labels_dict: "C:\\Maor Nanikashvili\\thesis_pipeline\\Pipeline\\input\\seg_mapping\\sentilet_color_mapper_config.yml"




