general_params:
  main_pipeline_path: '\\Pipeline\\'
  results_path: '\\Pipeline\\results'
  test_path: '\\Pipeline\\test'
  input_path: '\\Pipeline\\input'
  parallel_workers: 4

cubes_generator:
  transplant_method: 'max_score' # can be max_score, raffle
  test_folders_list: [ 'final_ver'
]
  materials_rgb_swir: "material_rgb_dict.yml"
  objects_base_rgb_scores_mat: "scores_mat_objects_dict_after_heur.pickle"
  obj_seg_rgb: "sentilet_color_mapper_config.yml"


