
functions:
  general_params:
    main_pipeline_path: '\\Pipeline\\'
    results_path: '\\Pipeline\\results'
    test_path: '\\Pipeline\\test'
    input_path: '\\Pipeline\\input'

  plot_multispectral_rgb:
    input_cubes_path: "\\Pipeline\\results\\cubes_generator\\final_ver\\Max_score\\cubes"
    gt_cubes_path: "\\Pipeline\\results\\sentilet_data\\full_dataset\\test\\multispectral"
    rgb_folder_path: "\\Pipeline\\results\\vgg19_clasiffier\\final_ver\\images"
    clu_folder_path: "\\Pipeline\\results\\heuristic_rgb_material_vector_v1\\final_ver\\clustered_rgb"
    material_rgb_folder_path: "\\Pipeline\\results\\cubes_generator\\final_ver\\Max_score\\masks\\rgb_masks"

  compare_metrics:
    gt_folder: "\\Pipeline\\results\\sentilet_data\\full_dataset\\test\\multispectral"
    predicted_folder: "\\Pipeline\\results\\cubes_generator\\final_ver\\raffle_score\\cubes_text"

  compare_materials_signatures:
    gt_folder: "\\Pipeline\\results\\sentilet_data\\full_dataset\\test\\multispectral"
    predicted_folder: "\\Pipeline\\results\\cubes_generator\\final_ver\\Max_score\\cubes_text"
    clu_folder_path: "\\Pipeline\\results\\heuristic_rgb_material_vector_v1\\final_ver\\clustered_rgb"
    data_dict_folder_path: "\\Pipeline\\test\\cubes_generator\\feb25_test_session_hvi_net_enhanced_full_materials_data_final_ver\\Max_score\\cubes_materials_dict"

  compare_metrics_rgb:
    gt_folder: "\\Pipeline\\results\\vgg19_clasiffier\\final_ver\\images"
    predicted_folder: "\\Pipeline\\results\\cubes_generator\\final_ver\\raffle_score\\masks\\rgb_masks"
