
functions:
  general_params:
    main_pipeline_path: '\\Pipeline\\'
    results_path: '\\Pipeline\\results'
    test_path: '\\Pipeline\\test'
    input_path: '\\Pipeline\\input'
    parallel_workers: 6

  vgg19_classifier:
    models_weights_path: "\\Pipeline\\input\\net_weights\\new_model_weights_lr_0.0001_775.pth"
    labels_mapping_file_name: 'sentilet_color_mapper_config.yml'
    test_folder_name : 'final_ver'
    num_classes: 6
    path_to_input_images_folder: "\\Pipeline\\results\\sentilet_data\\full_dataset\\test\\images"

  heuristic_object_material_vector:
    input_folder: 'seg_mapping'
    input_file: 'sentilet_color_mapper_config.yml'
    output_folder: 'seg_mapping'
    output_file: 'sentilet_color_mapper_config.csv'

  heuristic_rgb_material_vector_v1:
    create_new_materials_rgb_swir_dict: True
    create_new_clustered_rgb_folder: True
    use_clustered_base_rgb_folder: True
    create_new_clu_rgb_to_rgb_dict_and_unique_clu_rgb_per_obj: True
    create_new_scores_mat_with_heuristics: True
    hot_vector_name: "sentilet_color_mapper_config.csv"
    folder_names_list: [
'final_ver']
    object_data_file_name: 'sentilet_color_mapper_config.yml'


